deploy.sh: update to use fixed version for django-crispy-forms
The latest version 1.9.0 for python2.7 caused error like this:
 in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/django/test-crispy_forms-python2/lcr-report/lcr/urls.py", line 19, in <module>
    from . import accountviews
  File "/data/django/test-crispy_forms-python2/lcr-report/lcr/accountviews.py", line 25, in <module>
    from .forms import RegistrationForm
  File "/data/django/test-crispy_forms-python2/lcr-report/lcr/forms.py", line 7, in <module>
    from crispy_forms.helper import FormHelper
  File "/data/django/test-crispy_forms-python2/workspace/local/lib/python2.7/site-packages/crispy_forms/helper.py", line 7, in <module>
    from crispy_forms.layout import Layout
  File "/data/django/test-crispy_forms-python2/workspace/local/lib/python2.7/site-packages/crispy_forms/layout.py", line 334
    **kwargs,
            ^
SyntaxError: invalid syntax

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Change-Id: I9e69dd1a1a86cf4e0f499254b42790012fe328b1