deploy-with-python3.sh: update to use Django==1.11.17
to work with python3.7 for the problem reported here:

    SyntaxError: Generator expression must be parenthesized
    https://stackoverflow.com/questions/51265858/syntaxerror-generator-expression-must-be-parenthesized

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Change-Id: Id6c43a261a57dcfee007d80b9dbdee97141824f1